# Generated by Django 4.2.1 on 2023-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='https://sdn.geekzu.org/avatar/?size=40', max_length=500, verbose_name='头像链接'),
        ),
    ]
