services:
  server:
    image: skylersun/share-and-talk
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: skyler
      MYSQL_DATABASE: share_and_talk
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 10s
      retries: 10
#volumes:
#  db-data:
#secrets:
#  db-password:
#    file: db/password.txt

