# Generated by Django 4.2.1 on 2023-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softmetas',
            name='text',
            field=models.CharField(max_length=20, unique=True, verbose_name='软件分类名称'),
        ),
    ]
