# Generated by Django 4.2.1 on 2023-06-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
            },
        ),
        migrations.CreateModel(
            name='SoftMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='软件分类名称')),
            ],
            options={
                'verbose_name': '软件分类',
                'verbose_name_plural': '软件分类',
            },
        ),
        migrations.CreateModel(
            name='TopMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('text', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('read_times', models.IntegerField(verbose_name='阅读次数')),
                ('public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='点赞数')),
                ('meta_second', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='meta_second', to='blog.secondmetas', verbose_name='二级分类')),
                ('meta_top', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='meta_top', to='blog.topmetas', verbose_name='一级分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
