# Generated by Django 4.2.1 on 2023-06-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftMetas',
        ),
    ]
