# Generated by Django 4.2.1 on 2023-06-18 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_softmetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改日期'),
        ),
    ]
