# Generated by Django 4.2.1 on 2023-06-18 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_articles_read_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(editable=False, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='点赞数'),
        ),
    ]
