# Generated by Django 4.2.1 on 2023-06-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comments_options_alter_comments_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
