# Generated by Django 4.2.1 on 2023-06-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
