# Generated by Django 4.2.1 on 2023-06-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comments_options_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': '点赞', 'verbose_name_plural': '点赞'},
        ),
    ]
