# Generated by Django 4.2.1 on 2023-06-22 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0004_comments_modifydate_comments_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
